
module.exports={
    get: () => {
        return Promise.resolve( {
            data:
                [{
                    "classID": "da31f856-6fd1-4edb-9470-54e83cca2efe",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1572818590",
                    "duration": 53,
                    "title": "Tai Chi",
                    "metro": "Philadelphia",
                    "addr1": "383 Brickson Park Center",
                    "addr2": "6437",
                    "city": "Indianapolis",
                    "state": "IN",
                    "zip": "46239",
                    "price": 27.59,
                    "maxRegistrants": 29,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "intense"
                }, {
                    "classID": "df22d6b7-e469-46c3-8e48-115d7c0c27c2",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573688563",
                    "duration": 63,
                    "title": "Boxing",
                    "metro": "Philadelphia",
                    "addr1": "1097 Marcy Junction",
                    "city": "Tuscaloosa",
                    "state": "AL",
                    "zip": "35405",
                    "price": 4.82,
                    "maxRegistrants": 38,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "medium"
                }, {
                    "classID": "a39a03ca-6dec-4fd9-b462-863ace8cccce",
                    "instructor": "c923743e-d7fd-42af-9ae8-25e224cf9f94",
                    "startTime": "1572704458",
                    "duration": 80,
                    "title": "Hot Yoga",
                    "metro": "Los Angeles",
                    "addr1": "8018 Farwell Avenue",
                    "addr2": "4117",
                    "city": "Indianapolis",
                    "state": "IN",
                    "zip": "46216",
                    "price": 11.17,
                    "maxRegistrants": 32,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "medium"
                }, {
                    "classID": "b33359de-38a7-4486-9c25-eb9d32ec5a5e",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573165627",
                    "duration": 49,
                    "title": "Yoga",
                    "metro": "Philadelphia",
                    "addr1": "77 Waxwing Terrace",
                    "city": "El Paso",
                    "state": "TX",
                    "zip": "88574",
                    "price": 79.71,
                    "maxRegistrants": 19,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "intense"
                }, {
                    "classID": "e629d7b8-8108-4400-a1b3-b967a9d27562",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1573538678",
                    "duration": 79,
                    "title": "Tai Chi",
                    "metro": "Philadelphia",
                    "addr1": "05 Grim Point",
                    "city": "Valley Forge",
                    "state": "PA",
                    "zip": "19495",
                    "price": 72.82,
                    "maxRegistrants": 22,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "medium"
                }, {
                    "classID": "257f9612-ad5d-4333-b984-da451c288c36",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573045156",
                    "duration": 72,
                    "title": "Tai Chi",
                    "metro": "Los Angeles",
                    "addr1": "8 Mccormick Center",
                    "addr2": "6116",
                    "city": "Montgomery",
                    "state": "AL",
                    "zip": "36119",
                    "price": 42.0,
                    "maxRegistrants": 12,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "medium"
                }, {
                    "classID": "cc69fce8-6157-4f8a-94bd-0b2cb04a3771",
                    "instructor": "c968d877-8100-4f6b-bed6-1e6e6d585cbf",
                    "startTime": "1572870243",
                    "duration": 68,
                    "title": "Cardio Explosion",
                    "metro": "Asheville",
                    "addr1": "9129 Grim Street",
                    "city": "Oakland",
                    "state": "CA",
                    "zip": "94627",
                    "price": 31.13,
                    "maxRegistrants": 40,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "intense"
                }, {
                    "classID": "861698c7-f1a5-420c-8176-a69a854409ee",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1572722193",
                    "duration": 73,
                    "title": "Cardio Explosion",
                    "metro": "Los Angeles",
                    "addr1": "6 Mallory Place",
                    "city": "Jacksonville",
                    "state": "FL",
                    "zip": "32225",
                    "price": 49.37,
                    "maxRegistrants": 22,
                    "offerPunchcard": true,
                    "category": "Cardio",
                    "intensity": "light"
                }, {
                    "classID": "ffeb3806-91af-4e63-9baa-531d2b318267",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1572757808",
                    "duration": 87,
                    "title": "Pilates",
                    "metro": "Philadelphia",
                    "addr1": "75026 Ilene Avenue",
                    "city": "Las Vegas",
                    "state": "NV",
                    "zip": "89120",
                    "price": 16.99,
                    "maxRegistrants": 22,
                    "offerPunchcard": true,
                    "category": "Pilates",
                    "intensity": "light"
                }, {
                    "classID": "e2c72529-d916-45ce-98fd-eb5088f9b6e0",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573847587",
                    "duration": 77,
                    "title": "MMA",
                    "metro": "Philadelphia",
                    "addr1": "169 Melby Junction",
                    "city": "Brooklyn",
                    "state": "NY",
                    "zip": "11236",
                    "price": 95.53,
                    "maxRegistrants": 18,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "afe4db6f-6618-4dc7-806b-00da55f59a32",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1572611302",
                    "duration": 77,
                    "title": "Tai Chi",
                    "metro": "Iowa City",
                    "addr1": "639 Melody Plaza",
                    "city": "Davenport",
                    "state": "IA",
                    "zip": "52804",
                    "price": 84.97,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "d944726d-6101-4861-9fc2-ad14af12e558",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573709944",
                    "duration": 66,
                    "title": "Hot Yoga",
                    "metro": "San Diego",
                    "addr1": "1 Dennis Parkway",
                    "city": "Montgomery",
                    "state": "AL",
                    "zip": "36114",
                    "price": 28.38,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "intense"
                }, {
                    "classID": "93e5d380-230e-4472-874e-e21bb8e04d88",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1572880705",
                    "duration": 70,
                    "title": "Yoga",
                    "metro": "Asheville",
                    "addr1": "889 Summer Ridge Place",
                    "city": "Greensboro",
                    "state": "NC",
                    "zip": "27499",
                    "price": 11.36,
                    "maxRegistrants": 26,
                    "offerPunchcard": true,
                    "category": "Yoga",
                    "intensity": "medium"
                }, {
                    "classID": "1a6a1396-ca25-40b6-91d0-3237a64f3f93",
                    "instructor": "c968d877-8100-4f6b-bed6-1e6e6d585cbf",
                    "startTime": "1573229582",
                    "duration": 48,
                    "title": "Hot Yoga",
                    "metro": "San Diego",
                    "addr1": "988 Gateway Trail",
                    "city": "Garden Grove",
                    "state": "CA",
                    "zip": "92645",
                    "price": 56.25,
                    "maxRegistrants": 21,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "light"
                }, {
                    "classID": "a5eb8dd0-f40c-4bf8-ade4-8c5136046f9f",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1572842810",
                    "duration": 64,
                    "title": "CrossFit Extreme",
                    "metro": "Philadelphia",
                    "addr1": "8 Raven Hill",
                    "city": "Brooklyn",
                    "state": "NY",
                    "zip": "11236",
                    "price": 48.3,
                    "offerPunchcard": true,
                    "category": "CrossFit",
                    "intensity": "intense"
                }, {
                    "classID": "b57b432e-2400-43eb-99af-c00c75abae6f",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573664715",
                    "duration": 73,
                    "title": "HIIT it To the Limit!",
                    "metro": "Philadelphia",
                    "addr1": "92895 Rutledge Junction",
                    "addr2": "7",
                    "city": "Bonita Springs",
                    "state": "FL",
                    "zip": "34135",
                    "price": 96.65,
                    "offerPunchcard": false,
                    "category": "HIIT",
                    "intensity": "medium"
                }, {
                    "classID": "5957dd9a-7724-461f-a6fb-5c73425ffec5",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1572802904",
                    "duration": 80,
                    "title": "MMA",
                    "metro": "Los Angeles",
                    "addr1": "57 Brentwood Terrace",
                    "city": "Las Vegas",
                    "state": "NV",
                    "zip": "89178",
                    "price": 37.08,
                    "maxRegistrants": 12,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "2fbd369b-61d0-4b2b-b1ab-2b799f2adf0a",
                    "instructor": "c923743e-d7fd-42af-9ae8-25e224cf9f94",
                    "startTime": "1572683530",
                    "duration": 87,
                    "title": "Hot Yoga",
                    "metro": "Atlanta",
                    "addr1": "318 Marquette Center",
                    "addr2": "14156",
                    "city": "Fort Myers",
                    "state": "FL",
                    "zip": "33994",
                    "price": 77.4,
                    "maxRegistrants": 28,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "light"
                }, {
                    "classID": "bbf22b3f-6864-4475-bcdf-5e4baaccb9b3",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573757519",
                    "duration": 83,
                    "title": "Hot Yoga",
                    "metro": "Asheville",
                    "addr1": "1766 Fuller Point",
                    "city": "Kansas City",
                    "state": "MO",
                    "zip": "64193",
                    "price": 61.61,
                    "maxRegistrants": 20,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "intense"
                }, {
                    "classID": "73a5561a-8929-4764-87b3-8c2921e89cee",
                    "instructor": "3d3a1fdc-4fc4-4997-b1fb-47477541f0bc",
                    "startTime": "1573541867",
                    "duration": 83,
                    "title": "Yoga",
                    "metro": "Atlanta",
                    "addr1": "8 Fulton Alley",
                    "city": "Amarillo",
                    "state": "TX",
                    "zip": "79171",
                    "price": 1.0,
                    "maxRegistrants": 22,
                    "offerPunchcard": true,
                    "category": "Yoga",
                    "intensity": "medium"
                }, {
                    "classID": "ab4b13c1-7c9e-428b-bcae-ac12f429931a",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1572659944",
                    "duration": 65,
                    "title": "Cardio Explosion",
                    "metro": "Iowa City",
                    "addr1": "71 Manley Place",
                    "city": "Greensboro",
                    "state": "NC",
                    "zip": "27499",
                    "price": 35.73,
                    "maxRegistrants": 11,
                    "offerPunchcard": true,
                    "category": "Cardio",
                    "intensity": "light"
                }, {
                    "classID": "38e53e00-84c1-4b9f-b512-f9b3eeece1fe",
                    "instructor": "c968d877-8100-4f6b-bed6-1e6e6d585cbf",
                    "startTime": "1572850731",
                    "duration": 63,
                    "title": "Kickboxing",
                    "metro": "Philadelphia",
                    "addr1": "631 Dunning Place",
                    "addr2": "06",
                    "city": "Huntington",
                    "state": "WV",
                    "zip": "25711",
                    "price": 76.57,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "medium"
                }, {
                    "classID": "c45d2483-cad9-4220-860d-a5e3f8412f95",
                    "instructor": "c968d877-8100-4f6b-bed6-1e6e6d585cbf",
                    "startTime": "1573678605",
                    "duration": 62,
                    "title": "Pilates",
                    "metro": "San Diego",
                    "addr1": "40164 Katie Crossing",
                    "addr2": "98727",
                    "city": "Cleveland",
                    "state": "OH",
                    "zip": "44185",
                    "price": 69.09,
                    "maxRegistrants": 19,
                    "offerPunchcard": true,
                    "category": "Pilates",
                    "intensity": "light"
                }, {
                    "classID": "8cae7c7e-b2b7-455b-97e8-ca356a5989ad",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1572962184",
                    "duration": 67,
                    "title": "CrossFit Extreme",
                    "metro": "Iowa City",
                    "addr1": "51 Manitowish Crossing",
                    "city": "Dallas",
                    "state": "TX",
                    "zip": "75387",
                    "price": 12.04,
                    "maxRegistrants": 17,
                    "offerPunchcard": true,
                    "category": "CrossFit",
                    "intensity": "light"
                }, {
                    "classID": "c31398e0-fa47-488b-84d1-cd68a22f4393",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573513973",
                    "duration": 84,
                    "title": "Tai Chi",
                    "metro": "San Diego",
                    "addr1": "5566 Kenwood Plaza",
                    "city": "Wilmington",
                    "state": "DE",
                    "zip": "19892",
                    "price": 15.06,
                    "maxRegistrants": 20,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "intense"
                }, {
                    "classID": "a17ab2f9-7f3f-4b42-bd37-3e4b366ada93",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1572936228",
                    "duration": 49,
                    "title": "Yoga",
                    "metro": "Atlanta",
                    "addr1": "84634 Forest Dale Plaza",
                    "city": "Corona",
                    "state": "CA",
                    "zip": "92878",
                    "price": 73.06,
                    "offerPunchcard": true,
                    "category": "Yoga",
                    "intensity": "intense"
                }, {
                    "classID": "647b6f2e-3ff0-47a2-b557-07ac784fd882",
                    "instructor": "3d3a1fdc-4fc4-4997-b1fb-47477541f0bc",
                    "startTime": "1572860185",
                    "duration": 74,
                    "title": "Tai Chi",
                    "metro": "Los Angeles",
                    "addr1": "5 Division Center",
                    "addr2": "84058",
                    "city": "Honolulu",
                    "state": "HI",
                    "zip": "96835",
                    "price": 70.85,
                    "maxRegistrants": 11,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "medium"
                }, {
                    "classID": "ac8c1db4-0cdf-4e3d-b3ea-e27c6023d9e6",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1572856903",
                    "duration": 79,
                    "title": "CrossFit Extreme",
                    "metro": "Atlanta",
                    "addr1": "36428 Norway Maple Pass",
                    "city": "Greenville",
                    "state": "SC",
                    "zip": "29605",
                    "price": 22.82,
                    "offerPunchcard": false,
                    "category": "CrossFit",
                    "intensity": "medium"
                }, {
                    "classID": "de91b276-66c6-428c-a708-20ff0b652bf5",
                    "instructor": "c968d877-8100-4f6b-bed6-1e6e6d585cbf",
                    "startTime": "1573016028",
                    "duration": 70,
                    "title": "Spin",
                    "metro": "San Diego",
                    "addr1": "74 Warner Hill",
                    "city": "Cleveland",
                    "state": "OH",
                    "zip": "44111",
                    "price": 46.32,
                    "maxRegistrants": 11,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "2a5d11f7-ab97-49b0-902a-c758f1c3a549",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573275196",
                    "duration": 56,
                    "title": "Yoga",
                    "metro": "San Diego",
                    "addr1": "9260 Hanson Place",
                    "city": "Bakersfield",
                    "state": "CA",
                    "zip": "93311",
                    "price": 41.87,
                    "offerPunchcard": true,
                    "category": "Yoga",
                    "intensity": "medium"
                }, {
                    "classID": "2f0f412c-34ad-48f4-940e-6d03bb5118a6",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1572887574",
                    "duration": 74,
                    "title": "Cardio Explosion",
                    "metro": "Philadelphia",
                    "addr1": "05 Mcbride Lane",
                    "city": "Anchorage",
                    "state": "AK",
                    "zip": "99522",
                    "price": 47.67,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "light"
                }, {
                    "classID": "5eaf0a4d-c2fa-4795-afa2-4342f09da219",
                    "instructor": "c923743e-d7fd-42af-9ae8-25e224cf9f94",
                    "startTime": "1572969208",
                    "duration": 57,
                    "title": "Cardio Explosion",
                    "metro": "Atlanta",
                    "addr1": "6780 Meadow Valley Hill",
                    "city": "Portland",
                    "state": "OR",
                    "zip": "97271",
                    "price": 65.72,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "e49881e8-3f30-4ac1-908a-a4424e195fe4",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1572898413",
                    "duration": 86,
                    "title": "Yoga",
                    "metro": "Atlanta",
                    "addr1": "24 Utah Lane",
                    "city": "Birmingham",
                    "state": "AL",
                    "zip": "35210",
                    "price": 93.34,
                    "maxRegistrants": 26,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "light"
                }, {
                    "classID": "6afd2ad4-6af5-41cc-9697-442cf8027796",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1572814322",
                    "duration": 79,
                    "title": "Cardio Explosion",
                    "metro": "Los Angeles",
                    "addr1": "1 Center Trail",
                    "city": "Philadelphia",
                    "state": "PA",
                    "zip": "19131",
                    "price": 35.77,
                    "maxRegistrants": 20,
                    "offerPunchcard": true,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "61a1ad4e-6033-4d9c-9942-909cd62f0a88",
                    "instructor": "3d3a1fdc-4fc4-4997-b1fb-47477541f0bc",
                    "startTime": "1573018822",
                    "duration": 59,
                    "title": "Tai Chi",
                    "metro": "Iowa City",
                    "addr1": "914 American Center",
                    "addr2": "554",
                    "city": "Albuquerque",
                    "state": "NM",
                    "zip": "87105",
                    "price": 96.21,
                    "maxRegistrants": 29,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "70b3fe27-12b3-4ee6-a572-253c040f83a7",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1572643602",
                    "duration": 87,
                    "title": "Cardio Explosion",
                    "metro": "San Diego",
                    "addr1": "6 Saint Paul Alley",
                    "addr2": "5453",
                    "city": "Washington",
                    "state": "DC",
                    "zip": "20436",
                    "price": 54.01,
                    "maxRegistrants": 11,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "373ca7fe-3f15-476e-98c9-6993781e156b",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573155935",
                    "duration": 85,
                    "title": "Tai Chi",
                    "metro": "Atlanta",
                    "addr1": "18 Pearson Center",
                    "city": "Harrisburg",
                    "state": "PA",
                    "zip": "17126",
                    "price": 64.46,
                    "maxRegistrants": 25,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "23f2339d-5aaf-49ec-b9f2-37845fba76d9",
                    "instructor": "c968d877-8100-4f6b-bed6-1e6e6d585cbf",
                    "startTime": "1572913109",
                    "duration": 72,
                    "title": "Pilates",
                    "metro": "Los Angeles",
                    "addr1": "64 Fordem Center",
                    "city": "Bakersfield",
                    "state": "CA",
                    "zip": "93381",
                    "price": 19.31,
                    "maxRegistrants": 24,
                    "offerPunchcard": true,
                    "category": "Pilates",
                    "intensity": "intense"
                }, {
                    "classID": "47d8f6ba-ca98-4454-8142-4d05f5dab39f",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573313270",
                    "duration": 80,
                    "title": "CrossFit Extreme",
                    "metro": "Philadelphia",
                    "addr1": "139 Harbort Center",
                    "city": "Charleston",
                    "state": "SC",
                    "zip": "29403",
                    "price": 65.33,
                    "offerPunchcard": true,
                    "category": "CrossFit",
                    "intensity": "medium"
                }, {
                    "classID": "d5cc7b06-10c0-4021-828f-527a1640db01",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1572868726",
                    "duration": 86,
                    "title": "Tai Chi",
                    "metro": "San Diego",
                    "addr1": "340 Brentwood Avenue",
                    "city": "Washington",
                    "state": "DC",
                    "zip": "20540",
                    "price": 97.7,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "89e51842-9c48-4c36-92b6-9f5385cf6d38",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573827266",
                    "duration": 79,
                    "title": "Pilates",
                    "metro": "Asheville",
                    "addr1": "9452 Loeprich Court",
                    "city": "Pensacola",
                    "state": "FL",
                    "zip": "32575",
                    "price": 2.3,
                    "maxRegistrants": 14,
                    "offerPunchcard": false,
                    "category": "Pilates",
                    "intensity": "medium"
                }, {
                    "classID": "23b39ee4-7d1d-418b-8b36-c353b049b965",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573545177",
                    "duration": 53,
                    "title": "MMA",
                    "metro": "Atlanta",
                    "addr1": "6930 Monument Terrace",
                    "city": "Colorado Springs",
                    "state": "CO",
                    "zip": "80995",
                    "price": 68.26,
                    "maxRegistrants": 31,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "intense"
                }, {
                    "classID": "ef99f6dd-eded-41e6-8c31-7a352b333054",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573517621",
                    "duration": 79,
                    "title": "Kickboxing",
                    "metro": "Philadelphia",
                    "addr1": "9 Pond Crossing",
                    "city": "Jersey City",
                    "state": "NJ",
                    "zip": "07305",
                    "price": 46.08,
                    "maxRegistrants": 36,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "intense"
                }, {
                    "classID": "c695fc56-8bff-4db9-adbd-4455806c6e70",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1572743489",
                    "duration": 90,
                    "title": "Spin",
                    "metro": "Asheville",
                    "addr1": "84 Starling Pass",
                    "city": "Santa Barbara",
                    "state": "CA",
                    "zip": "93150",
                    "price": 55.67,
                    "maxRegistrants": 12,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "light"
                }, {
                    "classID": "1abe873f-ceb2-47bc-8a24-5df03d643cfe",
                    "instructor": "3d3a1fdc-4fc4-4997-b1fb-47477541f0bc",
                    "startTime": "1573646886",
                    "duration": 67,
                    "title": "Spin",
                    "metro": "Los Angeles",
                    "addr1": "5 Truax Place",
                    "city": "Greenville",
                    "state": "SC",
                    "zip": "29610",
                    "price": 30.32,
                    "maxRegistrants": 37,
                    "offerPunchcard": true,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "4584986f-e620-4dec-8066-ea8b84029d7f",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573420245",
                    "duration": 74,
                    "title": "Kickboxing",
                    "metro": "Asheville",
                    "addr1": "3 Starling Avenue",
                    "city": "Austin",
                    "state": "TX",
                    "zip": "78715",
                    "price": 61.29,
                    "maxRegistrants": 11,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "44a9f2fc-9e21-4264-9717-175d5609bdb1",
                    "instructor": "c923743e-d7fd-42af-9ae8-25e224cf9f94",
                    "startTime": "1573044235",
                    "duration": 59,
                    "title": "Cardio Explosion",
                    "metro": "Asheville",
                    "addr1": "991 Northridge Drive",
                    "addr2": "10296",
                    "city": "Allentown",
                    "state": "PA",
                    "zip": "18105",
                    "price": 54.1,
                    "maxRegistrants": 37,
                    "offerPunchcard": true,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "9dcf95d2-8b12-4927-942d-b9fca7d6c068",
                    "instructor": "3d3a1fdc-4fc4-4997-b1fb-47477541f0bc",
                    "startTime": "1572856566",
                    "duration": 60,
                    "title": "MMA",
                    "metro": "Atlanta",
                    "addr1": "32 Oneill Road",
                    "city": "El Paso",
                    "state": "TX",
                    "zip": "88530",
                    "price": 11.2,
                    "maxRegistrants": 11,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "c003c8c6-7fad-44be-a0d0-29ca3346bf9e",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1572708607",
                    "duration": 83,
                    "title": "Yoga",
                    "metro": "Atlanta",
                    "addr1": "8 Green Court",
                    "city": "Chicago",
                    "state": "IL",
                    "zip": "60630",
                    "price": 94.59,
                    "maxRegistrants": 30,
                    "offerPunchcard": true,
                    "category": "Yoga",
                    "intensity": "light"
                }, {
                    "classID": "9d730cfa-5388-4bb1-8516-98ecf33e4e97",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1573436999",
                    "duration": 45,
                    "title": "Spin",
                    "metro": "Iowa City",
                    "addr1": "263 Packers Way",
                    "city": "Roanoke",
                    "state": "VA",
                    "zip": "24040",
                    "price": 32.18,
                    "maxRegistrants": 17,
                    "offerPunchcard": true,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "943dc158-d39c-4490-9f76-baa747200b91",
                    "instructor": "c968d877-8100-4f6b-bed6-1e6e6d585cbf",
                    "startTime": "1573033687",
                    "duration": 56,
                    "title": "Cardio Explosion",
                    "metro": "Philadelphia",
                    "addr1": "01938 West Center",
                    "addr2": "637",
                    "city": "Suffolk",
                    "state": "VA",
                    "zip": "23436",
                    "price": 7.73,
                    "maxRegistrants": 23,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "light"
                }, {
                    "classID": "32122794-68e2-49f4-9b59-7d99ed02394f",
                    "instructor": "c923743e-d7fd-42af-9ae8-25e224cf9f94",
                    "startTime": "1573053985",
                    "duration": 87,
                    "title": "CrossFit Extreme",
                    "metro": "Philadelphia",
                    "addr1": "79 Moland Center",
                    "addr2": "26",
                    "city": "Tucson",
                    "state": "AZ",
                    "zip": "85715",
                    "price": 23.81,
                    "maxRegistrants": 14,
                    "offerPunchcard": false,
                    "category": "CrossFit",
                    "intensity": "intense"
                }, {
                    "classID": "72442280-f4d7-4e91-a412-0d135a4abed5",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573827663",
                    "duration": 48,
                    "title": "Tai Chi",
                    "metro": "Los Angeles",
                    "addr1": "734 Debs Avenue",
                    "city": "Louisville",
                    "state": "KY",
                    "zip": "40215",
                    "price": 99.29,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "ed8d53ca-4cae-40a9-98ec-0d6d0f40e29c",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573790931",
                    "duration": 64,
                    "title": "Yoga",
                    "metro": "Atlanta",
                    "addr1": "9 Truax Circle",
                    "city": "New York City",
                    "state": "NY",
                    "zip": "10249",
                    "price": 36.94,
                    "maxRegistrants": 36,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "light"
                }, {
                    "classID": "69322474-89a6-4ebd-ad97-b8c270abfc32",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573256752",
                    "duration": 52,
                    "title": "Cardio Explosion",
                    "metro": "Atlanta",
                    "addr1": "304 Esker Parkway",
                    "city": "Valdosta",
                    "state": "GA",
                    "zip": "31605",
                    "price": 85.14,
                    "maxRegistrants": 30,
                    "offerPunchcard": true,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "e66680bf-4b6e-43ef-a964-36c26f98fc64",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573461971",
                    "duration": 62,
                    "title": "Hot Yoga",
                    "metro": "Asheville",
                    "addr1": "36590 Jenna Pass",
                    "addr2": "377",
                    "city": "El Paso",
                    "state": "TX",
                    "zip": "88525",
                    "price": 3.9,
                    "maxRegistrants": 22,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "medium"
                }, {
                    "classID": "2694ea50-b73f-4917-9a4e-499afde9ef05",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573563580",
                    "duration": 84,
                    "title": "CrossFit Extreme",
                    "metro": "Atlanta",
                    "addr1": "346 Sunbrook Road",
                    "city": "Cleveland",
                    "state": "OH",
                    "zip": "44118",
                    "price": 16.65,
                    "offerPunchcard": true,
                    "category": "CrossFit",
                    "intensity": "light"
                }, {
                    "classID": "63c8bc83-e148-4740-8931-5c45c9ba9229",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1572627299",
                    "duration": 64,
                    "title": "Yoga",
                    "metro": "Philadelphia",
                    "addr1": "020 Scott Junction",
                    "city": "Phoenix",
                    "state": "AZ",
                    "zip": "85062",
                    "price": 81.0,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "intense"
                }, {
                    "classID": "bc5dbb82-56b2-4466-bb19-8a7e9f9e0fc1",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1573331939",
                    "duration": 55,
                    "title": "Yoga",
                    "metro": "Asheville",
                    "addr1": "9 8th Circle",
                    "city": "Plano",
                    "state": "TX",
                    "zip": "75074",
                    "price": 37.04,
                    "maxRegistrants": 24,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "light"
                }, {
                    "classID": "918b43ae-d077-433b-877e-172df7b890ec",
                    "instructor": "c923743e-d7fd-42af-9ae8-25e224cf9f94",
                    "startTime": "1573174271",
                    "duration": 45,
                    "title": "MMA",
                    "metro": "Asheville",
                    "addr1": "9844 Dwight Street",
                    "addr2": "8814",
                    "city": "Mc Keesport",
                    "state": "PA",
                    "zip": "15134",
                    "price": 22.96,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "intense"
                }, {
                    "classID": "d546c846-41ad-4926-b14e-5486c81ea04c",
                    "instructor": "c923743e-d7fd-42af-9ae8-25e224cf9f94",
                    "startTime": "1573773386",
                    "duration": 56,
                    "title": "HIIT it To the Limit!",
                    "metro": "Atlanta",
                    "addr1": "5351 Farmco Parkway",
                    "city": "Midland",
                    "state": "TX",
                    "zip": "79710",
                    "price": 62.74,
                    "maxRegistrants": 37,
                    "offerPunchcard": true,
                    "category": "HIIT",
                    "intensity": "intense"
                }, {
                    "classID": "aa284a74-af34-4494-950f-5273327b5dbe",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1572793058",
                    "duration": 67,
                    "title": "Spin",
                    "metro": "Los Angeles",
                    "addr1": "814 Autumn Leaf Center",
                    "city": "Cleveland",
                    "state": "OH",
                    "zip": "44111",
                    "price": 80.7,
                    "maxRegistrants": 25,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "5abdeb67-accf-48ec-b0c4-dcf7703c6c06",
                    "instructor": "c968d877-8100-4f6b-bed6-1e6e6d585cbf",
                    "startTime": "1572704137",
                    "duration": 57,
                    "title": "Hot Yoga",
                    "metro": "Iowa City",
                    "addr1": "75 Stone Corner Trail",
                    "city": "El Paso",
                    "state": "TX",
                    "zip": "88525",
                    "price": 29.22,
                    "maxRegistrants": 23,
                    "offerPunchcard": true,
                    "category": "Yoga",
                    "intensity": "light"
                }, {
                    "classID": "2dffd81c-2b3c-4d56-b3af-4527cfeecb66",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1572759030",
                    "duration": 55,
                    "title": "Yoga",
                    "metro": "Asheville",
                    "addr1": "79246 Basil Road",
                    "city": "San Antonio",
                    "state": "TX",
                    "zip": "78215",
                    "price": 47.98,
                    "maxRegistrants": 34,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "light"
                }, {
                    "classID": "a0d7ee53-ebec-4a38-9670-63ca5ea01b8e",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573606651",
                    "duration": 65,
                    "title": "Pilates",
                    "metro": "Atlanta",
                    "addr1": "44 Reinke Lane",
                    "city": "Columbus",
                    "state": "OH",
                    "zip": "43210",
                    "price": 60.4,
                    "maxRegistrants": 20,
                    "offerPunchcard": true,
                    "category": "Pilates",
                    "intensity": "light"
                }, {
                    "classID": "6681bd38-b4b1-43cb-b069-064ce31bce02",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1572592724",
                    "duration": 85,
                    "title": "Boxing",
                    "metro": "Philadelphia",
                    "addr1": "63367 Myrtle Street",
                    "city": "Largo",
                    "state": "FL",
                    "zip": "34643",
                    "price": 55.44,
                    "maxRegistrants": 19,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "intense"
                }, {
                    "classID": "26db9b90-4cf8-481a-a68e-f275c0329a9d",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1572945199",
                    "duration": 46,
                    "title": "Yoga",
                    "metro": "Asheville",
                    "addr1": "34807 Brown Circle",
                    "city": "Albany",
                    "state": "NY",
                    "zip": "12205",
                    "price": 90.98,
                    "maxRegistrants": 29,
                    "offerPunchcard": true,
                    "category": "Yoga",
                    "intensity": "intense"
                }, {
                    "classID": "5f02fd14-9e40-469c-89cf-6854c8be55f2",
                    "instructor": "3d3a1fdc-4fc4-4997-b1fb-47477541f0bc",
                    "startTime": "1573266830",
                    "duration": 73,
                    "title": "Cardio Explosion",
                    "metro": "Philadelphia",
                    "addr1": "221 Spenser Junction",
                    "addr2": "094",
                    "city": "Atlanta",
                    "state": "GA",
                    "zip": "30301",
                    "price": 39.86,
                    "maxRegistrants": 15,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "da7bbe9c-d951-4239-8a31-34b2fe6b7547",
                    "instructor": "3d3a1fdc-4fc4-4997-b1fb-47477541f0bc",
                    "startTime": "1572855288",
                    "duration": 56,
                    "title": "MMA",
                    "metro": "Iowa City",
                    "addr1": "07 Harper Drive",
                    "city": "Columbus",
                    "state": "OH",
                    "zip": "43284",
                    "price": 9.36,
                    "maxRegistrants": 23,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "65b456b2-8aa5-4214-87ea-b2bec7d96c86",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573498939",
                    "duration": 70,
                    "title": "Hot Yoga",
                    "metro": "San Diego",
                    "addr1": "6481 Merrick Hill",
                    "city": "New York City",
                    "state": "NY",
                    "zip": "10170",
                    "price": 0.7,
                    "offerPunchcard": true,
                    "category": "Yoga",
                    "intensity": "light"
                }, {
                    "classID": "cdb40f05-52a4-44df-ac71-2bd22f7f38b2",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573639186",
                    "duration": 53,
                    "title": "Hot Yoga",
                    "metro": "Asheville",
                    "addr1": "828 Texas Pass",
                    "addr2": "5",
                    "city": "Washington",
                    "state": "DC",
                    "zip": "20520",
                    "price": 76.98,
                    "maxRegistrants": 10,
                    "offerPunchcard": true,
                    "category": "Yoga",
                    "intensity": "light"
                }, {
                    "classID": "4b94372d-6eb8-4767-ac81-8433d4c6a559",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573703119",
                    "duration": 82,
                    "title": "Boxing",
                    "metro": "Atlanta",
                    "addr1": "56 Myrtle Road",
                    "city": "Honolulu",
                    "state": "HI",
                    "zip": "96825",
                    "price": 52.47,
                    "maxRegistrants": 24,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "medium"
                }, {
                    "classID": "751e065a-7836-4ad6-8b95-7ec20ecad2dc",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573164859",
                    "duration": 46,
                    "title": "Boxing",
                    "metro": "Asheville",
                    "addr1": "46117 Boyd Hill",
                    "city": "Jackson",
                    "state": "TN",
                    "zip": "38308",
                    "price": 49.54,
                    "maxRegistrants": 39,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "befc0665-3039-47e8-a0ef-c72b58398e1a",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573809718",
                    "duration": 49,
                    "title": "Tai Chi",
                    "metro": "Asheville",
                    "addr1": "078 Badeau Plaza",
                    "city": "Dallas",
                    "state": "TX",
                    "zip": "75287",
                    "price": 91.39,
                    "maxRegistrants": 12,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "medium"
                }, {
                    "classID": "dfcfb1e6-eca2-4be3-b94c-2dc199040056",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573192344",
                    "duration": 59,
                    "title": "CrossFit Extreme",
                    "metro": "Los Angeles",
                    "addr1": "1 Main Point",
                    "city": "Knoxville",
                    "state": "TN",
                    "zip": "37931",
                    "price": 69.66,
                    "offerPunchcard": false,
                    "category": "CrossFit",
                    "intensity": "medium"
                }, {
                    "classID": "07cc3f71-7879-4974-a347-d77c3b862fc2",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573144255",
                    "duration": 81,
                    "title": "CrossFit Extreme",
                    "metro": "Los Angeles",
                    "addr1": "6 Karstens Alley",
                    "city": "Nashville",
                    "state": "TN",
                    "zip": "37235",
                    "price": 9.94,
                    "maxRegistrants": 40,
                    "offerPunchcard": true,
                    "category": "CrossFit",
                    "intensity": "light"
                }, {
                    "classID": "927ce990-793a-4ef8-b48a-bc1812922c28",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573590959",
                    "duration": 87,
                    "title": "CrossFit Extreme",
                    "metro": "Asheville",
                    "addr1": "1857 Meadow Valley Center",
                    "city": "Birmingham",
                    "state": "AL",
                    "zip": "35285",
                    "price": 88.0,
                    "maxRegistrants": 33,
                    "offerPunchcard": false,
                    "category": "CrossFit",
                    "intensity": "intense"
                }, {
                    "classID": "cc5d372e-985a-44fe-8871-7b457614e61b",
                    "instructor": "c968d877-8100-4f6b-bed6-1e6e6d585cbf",
                    "startTime": "1573045279",
                    "duration": 85,
                    "title": "Pilates",
                    "metro": "Los Angeles",
                    "addr1": "974 Nevada Circle",
                    "city": "Little Rock",
                    "state": "AR",
                    "zip": "72209",
                    "price": 63.42,
                    "maxRegistrants": 34,
                    "offerPunchcard": false,
                    "category": "Pilates",
                    "intensity": "medium"
                }, {
                    "classID": "bbcbd03b-e1b8-4848-b81f-191bb4d6576b",
                    "instructor": "3d3a1fdc-4fc4-4997-b1fb-47477541f0bc",
                    "startTime": "1573455771",
                    "duration": 75,
                    "title": "Kickboxing",
                    "metro": "San Diego",
                    "addr1": "852 Waywood Drive",
                    "addr2": "2",
                    "city": "Las Vegas",
                    "state": "NV",
                    "zip": "89110",
                    "price": 5.65,
                    "maxRegistrants": 38,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "light"
                }, {
                    "classID": "bdfc92d3-1d57-4739-a8f8-7ebb3901c37b",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1573071370",
                    "duration": 79,
                    "title": "Spin",
                    "metro": "Atlanta",
                    "addr1": "8407 Maple Crossing",
                    "city": "Phoenix",
                    "state": "AZ",
                    "zip": "85040",
                    "price": 55.71,
                    "maxRegistrants": 36,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "intense"
                }, {
                    "classID": "1fafbb05-2712-410e-9d15-02157170a621",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1572678643",
                    "duration": 63,
                    "title": "Cardio Explosion",
                    "metro": "Atlanta",
                    "addr1": "9787 Ramsey Terrace",
                    "addr2": "5169",
                    "city": "Jamaica",
                    "state": "NY",
                    "zip": "11447",
                    "price": 75.84,
                    "maxRegistrants": 11,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "66f5614b-5fa1-44e4-821a-9c3efee6bff3",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1573778596",
                    "duration": 89,
                    "title": "Spin",
                    "metro": "San Diego",
                    "addr1": "92 Merrick Court",
                    "city": "Galveston",
                    "state": "TX",
                    "zip": "77554",
                    "price": 73.31,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "medium"
                }, {
                    "classID": "0af3b738-7fd2-491d-8cee-658efabe824b",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1573281293",
                    "duration": 72,
                    "title": "Spin",
                    "metro": "Philadelphia",
                    "addr1": "290 Holmberg Place",
                    "city": "San Jose",
                    "state": "CA",
                    "zip": "95108",
                    "price": 61.62,
                    "maxRegistrants": 16,
                    "offerPunchcard": false,
                    "category": "Cardio",
                    "intensity": "intense"
                }, {
                    "classID": "f7260023-3983-4831-bcaf-bb19716d40cb",
                    "instructor": "c923743e-d7fd-42af-9ae8-25e224cf9f94",
                    "startTime": "1573605503",
                    "duration": 68,
                    "title": "HIIT it To the Limit!",
                    "metro": "San Diego",
                    "addr1": "54276 Dennis Road",
                    "city": "Atlanta",
                    "state": "GA",
                    "zip": "30343",
                    "price": 63.67,
                    "maxRegistrants": 33,
                    "offerPunchcard": true,
                    "category": "HIIT",
                    "intensity": "intense"
                }, {
                    "classID": "02e3566e-6dc2-4651-ad49-809e8c5e34fb",
                    "instructor": "c968d877-8100-4f6b-bed6-1e6e6d585cbf",
                    "startTime": "1573025226",
                    "duration": 49,
                    "title": "MMA",
                    "metro": "San Diego",
                    "addr1": "03197 American Ash Crossing",
                    "city": "Portland",
                    "state": "OR",
                    "zip": "97240",
                    "price": 25.83,
                    "maxRegistrants": 37,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "intense"
                }, {
                    "classID": "c71bd58f-32f0-407b-890a-8bdb77eb8f80",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1573058474",
                    "duration": 89,
                    "title": "Yoga",
                    "metro": "Atlanta",
                    "addr1": "370 Meadow Valley Trail",
                    "addr2": "43831",
                    "city": "Huntington",
                    "state": "WV",
                    "zip": "25716",
                    "price": 12.89,
                    "maxRegistrants": 15,
                    "offerPunchcard": true,
                    "category": "Yoga",
                    "intensity": "medium"
                }, {
                    "classID": "631d4adc-8d9d-471f-8e70-9617db224be1",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573209438",
                    "duration": 69,
                    "title": "CrossFit Extreme",
                    "metro": "San Diego",
                    "addr1": "9 Holy Cross Crossing",
                    "city": "Dayton",
                    "state": "OH",
                    "zip": "45426",
                    "price": 79.66,
                    "maxRegistrants": 18,
                    "offerPunchcard": false,
                    "category": "CrossFit",
                    "intensity": "medium"
                }, {
                    "classID": "16b1b8c9-dab7-4708-bc20-a089ea1dd391",
                    "instructor": "c923743e-d7fd-42af-9ae8-25e224cf9f94",
                    "startTime": "1573120925",
                    "duration": 86,
                    "title": "Yoga",
                    "metro": "San Diego",
                    "addr1": "99191 Maple Road",
                    "city": "San Antonio",
                    "state": "TX",
                    "zip": "78260",
                    "price": 68.31,
                    "maxRegistrants": 37,
                    "offerPunchcard": true,
                    "category": "Yoga",
                    "intensity": "medium"
                }, {
                    "classID": "b5f86c40-796e-4b99-a359-b6a8d50c9810",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573390146",
                    "duration": 62,
                    "title": "HIIT it To the Limit!",
                    "metro": "Asheville",
                    "addr1": "897 Kennedy Circle",
                    "city": "Minneapolis",
                    "state": "MN",
                    "zip": "55458",
                    "price": 0.27,
                    "maxRegistrants": 38,
                    "offerPunchcard": true,
                    "category": "HIIT",
                    "intensity": "medium"
                }, {
                    "classID": "5c8bcaf1-517b-451c-9316-12dd48186180",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573810175",
                    "duration": 72,
                    "title": "Cardio Explosion",
                    "metro": "Iowa City",
                    "addr1": "8348 Eagle Crest Avenue",
                    "addr2": "75107",
                    "city": "Saint Paul",
                    "state": "MN",
                    "zip": "55127",
                    "price": 51.56,
                    "offerPunchcard": true,
                    "category": "Cardio",
                    "intensity": "intense"
                }, {
                    "classID": "695b5498-dc02-4475-bfed-ae94a7ed463f",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1572590570",
                    "duration": 59,
                    "title": "Tai Chi",
                    "metro": "San Diego",
                    "addr1": "41 Sloan Hill",
                    "city": "Chico",
                    "state": "CA",
                    "zip": "95973",
                    "price": 41.49,
                    "maxRegistrants": 33,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "intense"
                }, {
                    "classID": "ccc9b943-0757-4924-896f-d3deed53cd1e",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573178739",
                    "duration": 70,
                    "title": "Hot Yoga",
                    "metro": "Atlanta",
                    "addr1": "66 Oak Valley Park",
                    "city": "Springfield",
                    "state": "MA",
                    "zip": "01114",
                    "price": 30.89,
                    "maxRegistrants": 24,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "medium"
                }, {
                    "classID": "e7c3e6ca-f426-4290-8ddf-97f7ff4228ac",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573572546",
                    "duration": 89,
                    "title": "Yoga",
                    "metro": "Philadelphia",
                    "addr1": "9276 Eastwood Park",
                    "city": "Fort Myers",
                    "state": "FL",
                    "zip": "33913",
                    "price": 11.81,
                    "maxRegistrants": 38,
                    "offerPunchcard": false,
                    "category": "Yoga",
                    "intensity": "medium"
                }, {
                    "classID": "0190bbc6-7054-473c-bffe-df4d1fb8eaa2",
                    "instructor": "181e130b-5909-4d7e-85b6-9add5ed5c41e",
                    "startTime": "1573668115",
                    "duration": 48,
                    "title": "Tai Chi",
                    "metro": "Asheville",
                    "addr1": "60785 Del Mar Drive",
                    "city": "Clearwater",
                    "state": "FL",
                    "zip": "33758",
                    "price": 81.0,
                    "maxRegistrants": 13,
                    "offerPunchcard": false,
                    "category": "Martial Arts",
                    "intensity": "intense"
                }, {
                    "classID": "1622b47c-7c2c-4fd0-af46-2678f583cb69",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573691357",
                    "duration": 76,
                    "title": "HIIT it To the Limit!",
                    "metro": "Atlanta",
                    "addr1": "1 Arizona Road",
                    "city": "Durham",
                    "state": "NC",
                    "zip": "27717",
                    "price": 11.72,
                    "maxRegistrants": 24,
                    "offerPunchcard": false,
                    "category": "HIIT",
                    "intensity": "medium"
                }, {
                    "classID": "16ceb20b-ed62-47e6-8831-1f9e7bf7c273",
                    "instructor": "b2900b52-1219-4604-bc24-13abbb577659",
                    "startTime": "1573406732",
                    "duration": 59,
                    "title": "Boxing",
                    "metro": "Iowa City",
                    "addr1": "42345 East Street",
                    "city": "San Francisco",
                    "state": "CA",
                    "zip": "94116",
                    "price": 88.21,
                    "maxRegistrants": 31,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "intense"
                }, {
                    "classID": "5abd9b8c-fa6f-4e29-bb68-89164cd04ada",
                    "instructor": "3d3a1fdc-4fc4-4997-b1fb-47477541f0bc",
                    "startTime": "1573703338",
                    "duration": 59,
                    "title": "Kickboxing",
                    "metro": "Iowa City",
                    "addr1": "0 Rieder Road",
                    "city": "Orlando",
                    "state": "FL",
                    "zip": "32859",
                    "price": 73.86,
                    "offerPunchcard": true,
                    "category": "Martial Arts",
                    "intensity": "medium"
                }, {
                    "classID": "8e6c4d6e-7b3f-4441-a656-5bd6fd85bd37",
                    "instructor": "c968d877-8100-4f6b-bed6-1e6e6d585cbf",
                    "startTime": "1573678617",
                    "duration": 48,
                    "title": "CrossFit Extreme",
                    "metro": "Philadelphia",
                    "addr1": "086 Summerview Junction",
                    "city": "San Francisco",
                    "state": "CA",
                    "zip": "94154",
                    "price": 39.8,
                    "offerPunchcard": false,
                    "category": "CrossFit",
                    "intensity": "intense"
                }, {
                    "classID": "a90d7e57-2092-434f-9e06-9628d3797ebc",
                    "instructor": "19e5f25d-d56e-466e-98c9-8a20ecbb83b2",
                    "startTime": "1573745071",
                    "duration": 53,
                    "title": "CrossFit Extreme",
                    "metro": "Philadelphia",
                    "addr1": "0 Fallview Court",
                    "addr2": "276",
                    "city": "Omaha",
                    "state": "NE",
                    "zip": "68144",
                    "price": 43.26,
                    "maxRegistrants": 25,
                    "offerPunchcard": true,
                    "category": "CrossFit",
                    "intensity": "light"
                }, {
                    "classID": "72733eb8-849e-47c3-9945-a0d094da7495",
                    "instructor": "c923743e-d7fd-42af-9ae8-25e224cf9f94",
                    "startTime": "1573003730",
                    "duration": 77,
                    "title": "Pilates",
                    "metro": "Asheville",
                    "addr1": "52 Main Road",
                    "city": "Memphis",
                    "state": "TN",
                    "zip": "38109",
                    "price": 89.89,
                    "maxRegistrants": 32,
                    "offerPunchcard": true,
                    "category": "Pilates",
                    "intensity": "intense"
                }]
        } );
    }
};